/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/email/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the SMTP sender summary
         * @description Returns whether SMTP is configured at the process level (host env var present) and the From address operators advertise to end users. Credentials are deliberately never returned.
         */
        get: operations["admin-email-config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/oci-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Probe the compile dispatcher's OCI images
         * @description Returns one entry per language with its resolved image ref, the manifest probe status (ok | missing | unauthorized | unreachable) and the last-checked unix timestamp. Cached for 5 minutes ; pass ?force=1 to bypass the cache.
         */
        get: operations["admin-oci-images"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arxiv/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search arXiv.org
         * @description Server-side proxy for arXiv's Atom-XML query API. Parses the upstream feed + returns a compact JSON envelope so the SPA doesn't pull a full XML parser into the bundle.
         */
        get: operations["arxiv-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an SPA-side event to the doctor bus
         * @description Accepts a JSON event from the SPA's logbus client and republishes it onto the in-process event bus, which the SSE stream at GET /api/events fans out to subscribers. The SSE GET endpoint stays raw (streaming doesn't fit huma's typed model).
         */
        post: operations["client-event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns { status: "ok" } once the server is accepting requests. Unauthenticated — the operator's probe + the SPA both rely on this.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lsp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List languages with an available LSP server
         * @description Returns the set of language identifiers the SPA can use to open a WebSocket against /api/lsp/{lang}. Progressive enhancement gate.
         */
        get: operations["list-lsp-languages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the multi-file project scaffolds
         * @description Returns the curated catalogue of project templates surfaced in the SPA's "New project from template" picker. Each entry lists the files it would write + a size hint so the dialog can preview "5 files, 6.2 KB".
         */
        get: operations["list-project-templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's projects */
        get: operations["list-projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/bib/from-doi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a BibTeX entry from a DOI
         * @description Resolves a DOI through doi.org's content-negotiation API + appends the returned BibTeX to the target .bib (refs.bib by default).
         */
        post: operations["bib-from-doi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Legacy non-streaming chat stub
         * @description Returns a canned reply that demonstrates the assistant has access to the user's file context. The real provider lives behind the SSE /api/projects/{name}/ai/chat endpoint (raw, outside the typed API).
         */
        post: operations["chat-stub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a compile job
         * @description Schedules an ephemeral compile in the language's sandbox image. Returns the job ID immediately ; logs + result stream over Server-Sent Events at /api/projects/{name}/compile/{id} (raw, outside the typed API).
         */
        post: operations["start-compile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/compile/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an in-flight compile
         * @description Kills the in-flight job — the run goroutine sees ctx.Done() (host subprocess path) / the NATS exec `x` byte (workspace dispatch path), bails, and the SSE stream emits a "compile cancelled by user" log line followed by a result(success=false) event. Returns 204 on success ; 404 when the jobID is unknown or the job already terminated.
         */
        post: operations["cancel-compile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files in a project
         * @description Returns every file in the project as a flat list with relative paths. Directories appear with dir=true. Binary read/write of one file lands on /api/projects/{name}/files/{path...} (raw, outside the typed API).
         */
        get: operations["list-files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone the configured remote into the project working tree
         * @description Wipes any existing working tree and re-clones from the remote at the requested branch. Transient git errors land in the status body rather than as HTTP errors.
         */
        post: operations["git-clone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure the project's git remote
         * @description Persists remote URL, branch, provider, and (optional) PAT to the project sidecar. Returns the resulting status.
         */
        post: operations["git-config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Commit graph (HEAD-first)
         * @description Flat commit list with parent SHAs so the SPA can paint the lane graph client-side. Capped at limit (default 200, max 1000).
         */
        get: operations["git-log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pull the configured branch
         * @description Fast-forwards the working tree against origin. Transient errors land in the status body.
         */
        post: operations["git-pull"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-commit and push the configured branch
         * @description Stages every dirty + untracked file, commits with the caller's identity, then pushes to origin. Transient errors land in the status body.
         */
        post: operations["git-push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project git sync status
         * @description Returns the configured remote/branch, the dirty-file list, and the last sync timestamp.
         */
        get: operations["git-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a file's snapshot timeline
         * @description Returns the per-file edit history (newest first). Content is elided ; use the snapshot endpoint to fetch a single revision's text. Refuses .weft-loom/ paths (returns an empty list).
         */
        get: operations["list-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff two snapshots (or one snapshot vs the live file)
         * @description When `to` is omitted or equal to `live`, the right-hand side is the current on-disk file.
         */
        get: operations["diff-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach / rename / clear a label on a snapshot
         * @description Empty `label` clears the existing label.
         */
        post: operations["set-history-label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a file to a prior snapshot
         * @description Writes the snapshot's content back to the live file. Returns 204 on success. Refuses .weft-loom/ paths with 403 — pre-fix snapshots predate the privilege-escalation guard in handleWriteFile.
         */
        post: operations["restore-history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one snapshot's full content */
        get: operations["get-history-snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/notebook/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute one notebook cell in the workspace μVM
         * @description Dispatches the cell source as a shell command into the user's pre-spawned workspace μVM ; the wrapper binary is per-language. Returns captured stdout + stderr + exit code. Hard 60 s timeout so runaway loops don't pin the HTTP connection.
         */
        post: operations["notebook-exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/public-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current public-share token for the project
         * @description Returns the token + shareable URL when one exists ; 404 when the project has no active share.
         */
        get: operations["get-public-share"];
        put?: never;
        /**
         * Issue (or rotate) a public-share token for the project
         * @description Generates a fresh 32-hex-char token + persists the sidecar. If a token already existed for this project it is replaced (the prior URL stops working). Returns the new token, its shareable URL, and the RFC3339 issue time.
         */
        post: operations["create-public-share"];
        /**
         * Revoke the public-share token for the project
         * @description Removes the sidecar + drops the token from the in-memory index. Idempotent — returns 204 even when no share existed.
         */
        delete: operations["delete-public-share"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/scaffold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed a project from a multi-file template
         * @description Writes every file listed in the catalogue entry under the target project. By default the request 409s if any target path already exists in the project ; pass force=true to overwrite. The response carries the list of written files + an entry-point suggestion (main.tex / slides.md / README.md, in that priority).
         */
        post: operations["apply-project-template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/seed-claim/{path...}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomic seeder election for one (project, file)
         * @description Returns 200 + {elected:true} on the FIRST caller within the staleness window ; 409 + {elected:false} for everyone else. Used by the SPA to break the two-browsers-open-the-same-file race the client-side lowest-clientID heuristic couldn't catch reliably.
         */
        post: operations["seed-claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sharing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the ACL entries for a project
         * @description Returns the per-project share list. Any authed caller can GET — collaborators need to see whom else a project is shared with.
         */
        get: operations["list-sharing"];
        put?: never;
        /**
         * Invite or update a share entry
         * @description Adds a new ACL entry or replaces the role of an existing one. Only the project owner may mutate the ACL ; the first caller of a mutating endpoint becomes the owner.
         */
        post: operations["upsert-sharing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sharing/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a share entry
         * @description Idempotent : returns 204 whether or not the user was on the ACL. Only the project owner may mutate.
         */
        delete: operations["delete-sharing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/zotero/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relay a Zotero library export as BibTeX
         * @description Hits api.zotero.org/users/<id>/items?format=bibtex with the caller-supplied API key + streams the raw BibTeX bytes back. Response Content-Type is text/plain ; the SPA appends the result to refs.bib via the file API.
         */
        post: operations["zotero-sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChatInputBody.json
             */
            readonly $schema?: string;
            /** @description Currently-open file path (relative to the project root). Used to enrich the stub reply. */
            file?: string;
            /** @description Snapshot of the currently-open file. Used to enrich the stub reply. */
            file_content?: string;
            /** @description Conversation history ; the last entry is the user's current question. */
            messages: components["schemas"]["ChatMessage"][] | null;
        };
        ChatMessage: {
            /** @description Message text */
            content: string;
            /** @description Speaker role : system | user | assistant */
            role: string;
        };
        ChatOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ChatOutputBody.json
             */
            readonly $schema?: string;
            /** @description Model identifier echoed back to the SPA (always "stub-v0" for this endpoint). */
            model?: string;
            /** @description Stub reply text — the streaming /ai/chat endpoint is what wires to a real provider. */
            reply: string;
        };
        ClientEventInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ClientEventInputBody.json
             */
            readonly $schema?: string;
            /** @description Event component (e.g. "editor", "compile"). */
            component: string;
            /** @description Arbitrary structured fields ; merged with the bus event payload. */
            fields?: {
                [key: string]: unknown;
            };
            /** @description Severity hint : info | warn | error. Empty = info. */
            level?: string;
            /** @description Free-form message body. */
            message?: string;
            /** @description Project name when the event scopes to one. */
            project?: string;
            /** @description Event verb (e.g. "opened", "saved"). */
            verb: string;
        };
        DiffLine: {
            kind: string;
            /** Format: int64 */
            newLineNum: number;
            /** Format: int64 */
            oldLineNum: number;
            text: string;
        };
        DiffSummary: {
            /** Format: int64 */
            added: number;
            /** Format: int64 */
            removed: number;
        };
        DoiToBibInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DoiToBibInputBody.json
             */
            readonly $schema?: string;
            /** @description DOI in bare form (10.NNNN/suffix) or as a doi.org URL */
            doi: string;
            /** @description Optional target .bib file ; defaults to the first .bib in the project or refs.bib */
            target?: string;
        };
        EmailConfigResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EmailConfigResponse.json
             */
            readonly $schema?: string;
            configured: boolean;
            from?: string;
        };
        Entry: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Entry.json
             */
            readonly $schema?: string;
            author: string;
            content?: string;
            label?: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            ts: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FileOut: {
            /** @description True when the entry is a directory */
            dir: boolean;
            /** @description Path relative to the project root */
            path: string;
            /**
             * Format: int64
             * @description Size in bytes
             */
            size: number;
        };
        GitChange: {
            path: string;
            status: string;
        };
        GitConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitConfig.json
             */
            readonly $schema?: string;
            branch: string;
            provider: string;
            remote_url: string;
            token?: string;
        };
        GitLogEntry: {
            author: string;
            email: string;
            parents: string[] | null;
            ref_names?: string[] | null;
            sha: string;
            subject: string;
            /** Format: int64 */
            unix_time: number;
        };
        GitLogResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitLogResponse.json
             */
            readonly $schema?: string;
            branch: string;
            entries: components["schemas"]["GitLogEntry"][] | null;
            head_sha: string;
        };
        GitStatus: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GitStatus.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            ahead: number;
            /** Format: int64 */
            behind: number;
            branch: string;
            changes: components["schemas"]["GitChange"][] | null;
            configured: boolean;
            last_error?: string;
            /** Format: int64 */
            last_sync_unix?: number;
            provider: string;
            remote_url: string;
        };
        HealthzOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthzOutputBody.json
             */
            readonly $schema?: string;
            /** @description Always "ok" — liveness probe */
            status: string;
        };
        HistoryDiffOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryDiffOutputBody.json
             */
            readonly $schema?: string;
            from: string;
            hunks: components["schemas"]["Hunk"][] | null;
            summary: components["schemas"]["DiffSummary"];
            to: string;
        };
        HistoryEntryOut: {
            author?: string;
            label?: string;
            /** Format: int64 */
            size: number;
            /**
             * Format: date-time
             * @description RFC3339Nano timestamp
             */
            ts: string;
        };
        HistoryLabelInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryLabelInputBody.json
             */
            readonly $schema?: string;
            at: string;
            file: string;
            /** @description New label ; empty clears */
            label: string;
        };
        HistoryLabelOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryLabelOutputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            at: string;
            label: string;
        };
        HistoryListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryListOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["HistoryEntryOut"][] | null;
        };
        HistoryRestoreInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryRestoreInputBody.json
             */
            readonly $schema?: string;
            at: string;
            file: string;
        } & {
            [key: string]: unknown;
        };
        Hunk: {
            lines: components["schemas"]["DiffLine"][] | null;
            /** Format: int64 */
            newStart: number;
            /** Format: int64 */
            oldStart: number;
        };
        ListFilesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListFilesOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["FileOut"][] | null;
        };
        ListProjectsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListProjectsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ProjectOut"][] | null;
        };
        LspListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LspListOutputBody.json
             */
            readonly $schema?: string;
            /** @description Languages with a resolvable LSP server on this host */
            available: string[] | null;
        };
        NotebookExecInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NotebookExecInputBody.json
             */
            readonly $schema?: string;
            /** @description Notebook language_info.name (python | go | node | ruby | rust). Defaults to python when unknown. */
            language: string;
            /** @description Cell source ; passed verbatim to the chosen interpreter via shell quoting. */
            source: string;
        };
        NotebookExecResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NotebookExecResponse.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Process exit code ; 0 = success, 124 = our 60 s timeout.
             */
            exit_code: number;
            /** @description Captured stderr from the cell's interpreter. */
            stderr: string;
            /** @description Captured stdout from the cell's interpreter. */
            stdout: string;
        };
        OciImageStatus: {
            detail?: string;
            image: string;
            language: string;
            /** Format: int64 */
            last_checked_unix: number;
            status: string;
        };
        OciImagesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OciImagesOutputBody.json
             */
            readonly $schema?: string;
            images: components["schemas"]["OciImageStatus"][] | null;
        };
        ProjectOut: {
            /**
             * Format: date-time
             * @description Last modification time of the project directory
             */
            created_at: string;
            /** @description Detected language hint (latex / go / cpp / python / rust / javascript / markdown) */
            language?: string;
            /** @description Project name (filesystem-safe identifier) */
            name: string;
        };
        ProjectTemplate: {
            description: string;
            files: components["schemas"]["ScaffoldFile"][] | null;
            id: string;
            language: string;
            name: string;
        };
        ProjectTemplatesListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectTemplatesListOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ProjectTemplate"][] | null;
        };
        PublicShareOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PublicShareOutBody.json
             */
            readonly $schema?: string;
            /** @description RFC3339 timestamp the token was issued */
            created: string;
            /** @description 32-character hex share token */
            token: string;
            /** @description Shareable URL path (/public/<token>) */
            url: string;
        };
        ScaffoldFile: {
            path: string;
            /** Format: int64 */
            size: number;
        };
        ScaffoldInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScaffoldInputBody.json
             */
            readonly $schema?: string;
            /** @description Overwrite existing project files on path clash */
            force?: boolean;
            /** @description Catalogue entry id (e.g. latex-phd-thesis) */
            template_id: string;
        };
        ScaffoldOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScaffoldOutputBody.json
             */
            readonly $schema?: string;
            /** @description Existing project paths that would be overwritten (409 only) */
            clashes?: string[] | null;
            /** @description Suggested file to open in the editor */
            entry?: string;
            /** @description Human-readable error message (clash + write failures only) */
            error?: string;
            /** @description Files written (relative paths) */
            written?: string[] | null;
        };
        SeedClaimOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SeedClaimOutputBody.json
             */
            readonly $schema?: string;
            /** @description True when the caller is the elected seeder ; false when another caller already holds the claim. */
            elected: boolean;
        };
        SharingListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SharingListOutputBody.json
             */
            readonly $schema?: string;
            shares: components["schemas"]["SharingShareOut"][] | null;
        };
        SharingShareOut: {
            /** @description editor | commenter | viewer */
            role: string;
            /** @description User subject (dex sub claim) */
            user: string;
        };
        SharingUpsertInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SharingUpsertInputBody.json
             */
            readonly $schema?: string;
            /** @description One of editor | commenter | viewer */
            role: string;
            /** @description User subject (dex sub claim) to invite or update */
            user: string;
        };
        StartCompileBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StartCompileBody.json
             */
            readonly $schema?: string;
            /** @description Bibliography processor : bibtex | biber. Defaults to bibtex. */
            bib?: string;
            /** @description Optional verbatim shell command — overrides the language's default when set. Inside the workspace μVM, the dispatcher runs sh -c <command>. */
            command?: string;
            /** @description LaTeX engine to invoke for the latex language : pdflatex | lualatex | xelatex. Defaults to pdflatex. */
            engine?: string;
            /** @description Main source file (e.g. main.tex, main.go). Per-language default applies when empty. */
            entry?: string;
            /** @description Appended to the language's default build command. */
            extra_args?: string[] | null;
            /** @description Sandbox image picker (latex / go / cpp / python / rust / javascript). Required. */
            language: string;
        };
        StartCompileOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StartCompileOutputBody.json
             */
            readonly $schema?: string;
            /** @description Job identifier ; tail logs via GET /api/projects/{name}/compile/{id} (SSE). */
            id: string;
        };
        ZoteroSyncInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ZoteroSyncInputBody.json
             */
            readonly $schema?: string;
            /** @description Zotero API key with library:read permission */
            api_key: string;
            /** @description Reserved for future use ; current API streams the raw BibTeX back to the client */
            target?: string;
            /** @description Numeric Zotero user ID (from zotero.org/settings/keys) */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-email-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailConfigResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-oci-images": {
        parameters: {
            query?: {
                /** @description Force a fresh probe (bypass the 5-minute cache) */
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OciImagesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "arxiv-search": {
        parameters: {
            query?: {
                /** @description Search query (passed to arXiv as all:<q>) */
                q?: string;
                /** @description Max results (default 10, capped 50) */
                max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "client-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientEventInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-lsp-languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LspListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-project-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTemplatesListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "bib-from-doi": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoiToBibInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "chat-stub": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-compile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCompileBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCompileOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-compile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
                /** @description Job identifier returned by start-compile */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFilesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-clone": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-log": {
        parameters: {
            query?: {
                /** @description Maximum number of commits to return (1..1000) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLogResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-pull": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-push": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "git-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-history": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "diff-history": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
                /** @description RFC3339 / RFC3339Nano timestamp of the older snapshot */
                from?: string;
                /** @description RFC3339 timestamp of the newer snapshot, or 'live' (default) for the on-disk file */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDiffOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-history-label": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryLabelInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryLabelOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "restore-history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryRestoreInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-history-snapshot": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
                /** @description RFC3339 / RFC3339Nano timestamp of the snapshot */
                at?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "notebook-exec": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotebookExecInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookExecResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "apply-project-template": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScaffoldInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "seed-claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
                /** @description File path relative to the project root ; matches the {path...} suffix wildcard. */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedClaimOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upsert-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SharingUpsertInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
                /** @description User subject to remove from the ACL */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "zotero-sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoteroSyncInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
