// api.ts — typed client built on openapi-fetch. The shape comes from
// api.gen.ts (generated by `npm run gen-api` against ../openapi.json).
//
// Same pattern as weft-webui's lib/api.ts : one createClient call,
// re-exported as `api`, and one helper per operation that hides
// the openapi-fetch envelope so consumers write
// `await listProjects()` instead of
// `await api.GET('/api/projects')` + status check + body destructure.

import createClient from 'openapi-fetch';
import type { paths } from './api.gen';

export const api = createClient<paths>({ baseUrl: '' });

export type Project = NonNullable<
  paths['/api/projects']['get']['responses']['200']['content']['application/json']['items']
>[number];

export type File = NonNullable<
  paths['/api/projects/{name}/files']['get']['responses']['200']['content']['application/json']['items']
>[number];

export async function listProjects(): Promise<Project[]> {
  const { data, error } = await api.GET('/api/projects');
  if (error) throw new Error(`list-projects: ${JSON.stringify(error)}`);
  return data.items ?? [];
}

// renameProject moves a project from oldName to newName for the
// caller. Returns the resulting projectOut (Name + Language +
// CreatedAt) so the UI can patch its local list without a full
// re-fetch. Throws on 400 (invalid name), 409 (dest exists), or any
// other non-2xx — callers should surface the message inline.
export async function renameProject(
  oldName: string,
  newName: string,
): Promise<Project> {
  const { data, error } = await api.POST('/api/projects/{name}/rename', {
    params: { path: { name: oldName } },
    body: { newName },
  });
  if (error) throw new Error(`rename-project: ${JSON.stringify(error)}`);
  return data as Project;
}

export async function listFiles(project: string): Promise<File[]> {
  const { data, error } = await api.GET('/api/projects/{name}/files', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`list-files: ${JSON.stringify(error)}`);
  return data.items ?? [];
}

// Raw read/write/delete bypass the typed huma surface — the openapi
// spec only documents the high-level list. Editor + FileExplorer talk
// to these directly.
export async function writeFile(
  project: string,
  path: string,
  body: string | Uint8Array | Blob,
  contentType: string = 'text/plain',
): Promise<void> {
  const url = `/api/projects/${encodeURIComponent(project)}/files/${path
    .split('/')
    .map(encodeURIComponent)
    .join('/')}`;
  let payload: BodyInit;
  if (typeof body === 'string') payload = body;
  else if (body instanceof Blob) payload = body;
  else payload = new Blob([body as unknown as BlobPart], { type: contentType });
  const resp = await fetch(url, {
    method: 'PUT',
    headers: { 'Content-Type': contentType },
    body: payload,
  });
  if (!resp.ok) {
    throw new Error(`write-file ${resp.status}: ${await resp.text()}`);
  }
}

export async function readFile(
  project: string,
  path: string,
): Promise<string> {
  const url = `/api/projects/${encodeURIComponent(project)}/files/${path
    .split('/')
    .map(encodeURIComponent)
    .join('/')}`;
  const resp = await fetch(url);
  if (!resp.ok) {
    throw new Error(`read-file ${resp.status}: ${await resp.text()}`);
  }
  return resp.text();
}

export async function deleteFile(project: string, path: string): Promise<void> {
  const url = `/api/projects/${encodeURIComponent(project)}/files/${path
    .split('/')
    .map(encodeURIComponent)
    .join('/')}`;
  const resp = await fetch(url, { method: 'DELETE' });
  // Treat 404 as success — the file's already gone (concurrent
  // delete from another tab, e.g.).
  if (!resp.ok && resp.status !== 404) {
    throw new Error(`delete-file ${resp.status}: ${await resp.text()}`);
  }
}

export interface CompileSpec {
  language: string;
  entry?: string;
  extra_args?: string[];
  // command — verbatim shell command that REPLACES the language's
  // default when set. Populated by the SettingsPanel "Compile
  // commands" section. Empty string falls back to the built-in
  // per-language command.
  command?: string;
  // engine — LaTeX engine selector (pdflatex / lualatex / xelatex).
  // Populated by CompilerSelector ; ignored by the backend for
  // non-LaTeX languages. Empty defaults to pdflatex.
  engine?: string;
  // bib — bibliography processor (bibtex / biber). Same scope as
  // engine — LaTeX only, backend default = bibtex.
  bib?: string;
}

export async function startCompile(
  project: string,
  spec: CompileSpec,
): Promise<string> {
  const { data, error } = await api.POST('/api/projects/{name}/compile', {
    params: { path: { name: project } },
    body: spec,
  });
  if (error) throw new Error(`start-compile: ${JSON.stringify(error)}`);
  return data.id;
}

// cancelCompile pulls the plug on a still-running compile job. Hits
// the raw POST endpoint (outside the typed huma surface — the
// handler returns 204 no-content, which doesn't fit the typed-client
// envelope as cleanly). 404 means the job already finished — we
// swallow it so the UI's "Cancel" button feels idempotent.
export async function cancelCompile(project: string, jobID: string): Promise<void> {
  const url = `/api/projects/${encodeURIComponent(project)}/compile/${encodeURIComponent(jobID)}/cancel`;
  const resp = await fetch(url, { method: 'POST' });
  if (!resp.ok && resp.status !== 404) {
    throw new Error(`cancel-compile ${resp.status}: ${await resp.text()}`);
  }
}

// --- chktex strict LaTeX linter ---------------------------------------

// ChktexDiagnostic mirrors the server-side wire shape (line/col are
// 1-based, severity is the LSP-flavoured bucket). The editor's lint
// extension converts the 1-based positions to 0-based document
// offsets the same way it does for LSP diagnostics.
export interface ChktexDiagnostic {
  line: number;
  col: number;
  code: number;
  message: string;
  severity: 'error' | 'warning' | 'info';
}

export interface ChktexResult {
  diagnostics: ChktexDiagnostic[];
  // available : false when the loom-server host doesn't have the
  // chktex binary installed. SPA shows a one-time "strict linting
  // unavailable" tooltip in that case ; diagnostics will always be
  // empty when this is false.
  available: boolean;
}

// runChktex pipes the current editor buffer at the strict LaTeX
// linter (chktex) on the loom-server host. Returns { diagnostics,
// available } — when the host has no chktex binary the call still
// succeeds (200) with `available: false` + an empty array, so the
// caller can treat "unavailable" as a quiet no-op rather than an
// error path. Errors are limited to network failures + 5xx.
export async function runChktex(
  project: string,
  content: string,
  opts?: { signal?: AbortSignal },
): Promise<ChktexResult> {
  const { data, error } = await api.POST('/api/projects/{name}/lint/chktex', {
    params: { path: { name: project } },
    body: { content },
    signal: opts?.signal,
  });
  if (error) throw new Error(`chktex: ${JSON.stringify(error)}`);
  return {
    diagnostics: (data.diagnostics ?? []) as ChktexDiagnostic[],
    available: Boolean(data.available),
  };
}

// --- Sharing (per-project ACL editor) ---------------------------------

export type ShareRole = 'editor' | 'commenter' | 'viewer';

export interface Share {
  user: string;
  role: ShareRole;
}

export async function listSharing(project: string): Promise<Share[]> {
  const { data, error } = await api.GET('/api/projects/{name}/sharing', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`list-sharing: ${JSON.stringify(error)}`);
  return (data.shares ?? []) as Share[];
}

export async function upsertShare(
  project: string,
  user: string,
  role: ShareRole,
): Promise<Share[]> {
  const { data, error } = await api.POST('/api/projects/{name}/sharing', {
    params: { path: { name: project } },
    body: { user, role },
  });
  if (error) throw new Error(`upsert-sharing: ${JSON.stringify(error)}`);
  return (data.shares ?? []) as Share[];
}

export async function deleteShare(project: string, user: string): Promise<void> {
  const { error, response } = await api.DELETE('/api/projects/{name}/sharing/{user}', {
    params: { path: { name: project, user } },
  });
  // 204 No Content is success — openapi-fetch surfaces it via response.ok.
  if (error && !response.ok) {
    throw new Error(`delete-sharing: ${JSON.stringify(error)}`);
  }
}

// --- User-defined snippets (per project) ------------------------------
//
// Backed by the .weft-loom/snippets.json sidecar (see api_snippets.go).
// The SPA merges these with the curated SNIPPETS[] defaults in
// snippets.ts before feeding the CodeMirror completion source — see
// mergeUserSnippets there.

export interface UserSnippet {
  id: string;
  label: string;
  body: string;
  hotkey?: string;
  scope?: string;
}

export async function listSnippets(project: string): Promise<UserSnippet[]> {
  const { data, error } = await api.GET('/api/projects/{name}/snippets', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`list-snippets: ${JSON.stringify(error)}`);
  return (data.snippets ?? []) as UserSnippet[];
}

// upsertSnippet returns the persisted snippet (with the server-
// allocated id when the caller didn't supply one). Pass `id` to
// replace an existing entry, omit it to create a fresh one.
export async function upsertSnippet(
  project: string,
  snippet: { id?: string; label: string; body: string; hotkey?: string; scope?: string },
): Promise<UserSnippet> {
  const { data, error } = await api.POST('/api/projects/{name}/snippets', {
    params: { path: { name: project } },
    body: snippet,
  });
  if (error) throw new Error(`upsert-snippet: ${JSON.stringify(error)}`);
  return data as UserSnippet;
}

export async function deleteSnippet(project: string, id: string): Promise<void> {
  const { error, response } = await api.DELETE('/api/projects/{name}/snippets/{id}', {
    params: { path: { name: project, id } },
  });
  // 204 No Content is success — openapi-fetch surfaces it via response.ok.
  if (error && !response.ok) {
    throw new Error(`delete-snippet: ${JSON.stringify(error)}`);
  }
}

// --- Public share (read-only token link) ------------------------------

export interface PublicShareRecord {
  token: string;
  url: string;
  created: string;
}

export async function createPublicShare(project: string): Promise<PublicShareRecord> {
  const { data, error } = await api.POST('/api/projects/{name}/public-share', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`create-public-share: ${JSON.stringify(error)}`);
  return data as PublicShareRecord;
}

// getPublicShare reads the current token. 404 means no link exists yet ;
// we map that to `null` so the caller's "no public link" UI branch can
// trigger on a missing share without an error popup.
export async function getPublicShare(project: string): Promise<PublicShareRecord | null> {
  const { data, error, response } = await api.GET('/api/projects/{name}/public-share', {
    params: { path: { name: project } },
  });
  if (response.status === 404) return null;
  if (error) throw new Error(`get-public-share: ${JSON.stringify(error)}`);
  return (data ?? null) as PublicShareRecord | null;
}

export async function deletePublicShare(project: string): Promise<void> {
  const { error, response } = await api.DELETE('/api/projects/{name}/public-share', {
    params: { path: { name: project } },
  });
  if (error && !response.ok) {
    throw new Error(`delete-public-share: ${JSON.stringify(error)}`);
  }
}

// --- History (per-file snapshot timeline) -----------------------------

export interface HistoryEntry {
  ts: string;
  author: string;
  size: number;
  label?: string;
}

export interface HistorySnapshot extends HistoryEntry {
  content?: string;
}

export interface HistoryDiffLine {
  kind: 'add' | 'remove' | 'context';
  text: string;
  oldLineNum: number;
  newLineNum: number;
}

export interface HistoryDiffHunk {
  oldStart: number;
  newStart: number;
  lines: HistoryDiffLine[];
}

export interface HistoryDiff {
  from: string;
  to: string;
  summary: { added: number; removed: number };
  hunks: HistoryDiffHunk[];
}

export async function listHistory(project: string, file: string): Promise<HistoryEntry[]> {
  const { data, error } = await api.GET('/api/projects/{name}/history', {
    params: { path: { name: project }, query: { file } },
  });
  if (error) throw new Error(`list-history: ${JSON.stringify(error)}`);
  return (data.entries ?? []) as HistoryEntry[];
}

export async function getHistorySnapshot(
  project: string,
  file: string,
  at: string,
): Promise<HistorySnapshot> {
  const { data, error } = await api.GET('/api/projects/{name}/history/snapshot', {
    params: { path: { name: project }, query: { file, at } },
  });
  if (error) throw new Error(`get-history-snapshot: ${JSON.stringify(error)}`);
  return data as HistorySnapshot;
}

export async function diffHistory(
  project: string,
  file: string,
  from: string,
  to: string,
): Promise<HistoryDiff> {
  const { data, error } = await api.GET('/api/projects/{name}/history/diff', {
    params: { path: { name: project }, query: { file, from, to } },
  });
  if (error) throw new Error(`diff-history: ${JSON.stringify(error)}`);
  // The wire shape's `hunks` may come back as null when there's no
  // diff ; normalise to [] so callers can hunks.length without a
  // nullish dance.
  const d = data as HistoryDiff & { hunks: HistoryDiffHunk[] | null };
  return { ...d, hunks: d.hunks ?? [] };
}

export async function setHistoryLabel(
  project: string,
  file: string,
  at: string,
  label: string,
): Promise<{ at: string; label: string }> {
  const { data, error } = await api.POST('/api/projects/{name}/history/label', {
    params: { path: { name: project } },
    body: { file, at, label },
  });
  if (error) throw new Error(`set-history-label: ${JSON.stringify(error)}`);
  return data as { at: string; label: string };
}

export async function restoreHistory(
  project: string,
  file: string,
  at: string,
): Promise<void> {
  const { error, response } = await api.POST('/api/projects/{name}/history/restore', {
    params: { path: { name: project } },
    body: { file, at },
  });
  if (error && !response.ok) {
    throw new Error(`restore-history: ${JSON.stringify(error)}`);
  }
}

// --- Bibliography helpers ---------------------------------------------
//
// The three bib endpoints (bib-from-doi, zotero-sync, arxiv-search) are
// typed in the OpenAPI spec as `application/json: string` with
// `contentEncoding: base64` — huma annotates the `Body []byte`
// envelope that way. On the wire the server actually emits structured
// JSON (bib-from-doi, arxiv-search) or raw text/plain BibTeX
// (zotero-sync), so we bypass openapi-fetch's type-driven parsing
// here and read the raw response.

export interface DoiImportResult {
  entry: string;
  target: string;
  appended: boolean;
}

export async function bibFromDoi(
  project: string,
  doi: string,
  target?: string,
): Promise<DoiImportResult> {
  const url = `/api/projects/${encodeURIComponent(project)}/bib/from-doi`;
  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(target ? { doi, target } : { doi }),
  });
  if (!resp.ok) {
    const body = await resp.json().catch(() => ({}));
    throw new Error(body?.error ?? `bib-from-doi: HTTP ${resp.status}`);
  }
  return (await resp.json()) as DoiImportResult;
}

// zoteroSync returns the raw BibTeX bytes (text/plain) so the caller
// can append them to refs.bib via the file API.
export async function zoteroSync(
  project: string,
  userID: string,
  apiKey: string,
): Promise<string> {
  const url = `/api/projects/${encodeURIComponent(project)}/zotero/sync`;
  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ user_id: userID, api_key: apiKey }),
  });
  if (!resp.ok) {
    const body = await resp.json().catch(() => ({}));
    throw new Error(body?.error ?? `zotero-sync: HTTP ${resp.status}`);
  }
  return resp.text();
}

export interface ArxivEntry {
  id: string;
  title: string;
  authors: string[];
  summary: string;
  year: string;
  primaryCategory: string;
}

export async function arxivSearch(
  q: string,
  max: number = 20,
): Promise<ArxivEntry[]> {
  const url = `/api/arxiv/search?q=${encodeURIComponent(q)}&max=${max}`;
  const resp = await fetch(url);
  if (!resp.ok) {
    const body = await resp.json().catch(() => ({}));
    throw new Error(body?.error ?? `arxiv-search: HTTP ${resp.status}`);
  }
  const data = (await resp.json()) as { entries?: ArxivEntry[] };
  return data.entries ?? [];
}

// --- Project git remote (status / config / clone / pull / push / log) -

export type GitStatus = NonNullable<
  paths['/api/projects/{name}/git/status']['get']['responses']['200']['content']['application/json']
>;

export type GitConfig = NonNullable<
  paths['/api/projects/{name}/git/config']['post']['requestBody']
>['content']['application/json'];

export type GitLogResponse = NonNullable<
  paths['/api/projects/{name}/git/log']['get']['responses']['200']['content']['application/json']
>;

export type GitLogEntry = NonNullable<GitLogResponse['entries']>[number];

export async function gitStatus(project: string): Promise<GitStatus> {
  const { data, error } = await api.GET('/api/projects/{name}/git/status', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`git-status: ${JSON.stringify(error)}`);
  return data;
}

export async function gitConfig(project: string, cfg: GitConfig): Promise<GitStatus> {
  const { data, error } = await api.POST('/api/projects/{name}/git/config', {
    params: { path: { name: project } },
    body: cfg,
  });
  if (error) throw new Error(`git-config: ${JSON.stringify(error)}`);
  return data;
}

export async function gitClone(project: string, cfg: GitConfig): Promise<GitStatus> {
  const { data, error } = await api.POST('/api/projects/{name}/git/clone', {
    params: { path: { name: project } },
    body: cfg,
  });
  if (error) throw new Error(`git-clone: ${JSON.stringify(error)}`);
  return data;
}

export async function gitPull(project: string): Promise<GitStatus> {
  const { data, error } = await api.POST('/api/projects/{name}/git/pull', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`git-pull: ${JSON.stringify(error)}`);
  return data;
}

export async function gitPush(project: string): Promise<GitStatus> {
  const { data, error } = await api.POST('/api/projects/{name}/git/push', {
    params: { path: { name: project } },
  });
  if (error) throw new Error(`git-push: ${JSON.stringify(error)}`);
  return data;
}

export async function gitLog(project: string, limit = 200): Promise<GitLogResponse> {
  const { data, error } = await api.GET('/api/projects/{name}/git/log', {
    params: { path: { name: project }, query: { limit } },
  });
  if (error) throw new Error(`git-log: ${JSON.stringify(error)}`);
  return data;
}

// --- Project templates + scaffold -------------------------------------

export type ProjectTemplate = NonNullable<
  NonNullable<
    paths['/api/project-templates']['get']['responses']['200']['content']['application/json']['items']
  >
>[number];

export type ScaffoldInput = NonNullable<
  paths['/api/projects/{name}/scaffold']['post']['requestBody']
>['content']['application/json'];

export type ScaffoldResult = NonNullable<
  paths['/api/projects/{name}/scaffold']['post']['responses']['200']['content']['application/json']
>;

// ScaffoldClashError surfaces the 409 path distinctly so the caller
// can render the clash list without re-parsing the error envelope.
export class ScaffoldClashError extends Error {
  clashes: string[];
  constructor(clashes: string[], message: string) {
    super(message);
    this.name = 'ScaffoldClashError';
    this.clashes = clashes;
  }
}

export async function listProjectTemplates(): Promise<ProjectTemplate[]> {
  const { data, error } = await api.GET('/api/project-templates');
  if (error) throw new Error(`list-project-templates: ${JSON.stringify(error)}`);
  return data.items ?? [];
}

export async function applyScaffold(
  project: string,
  opts: ScaffoldInput,
): Promise<ScaffoldResult> {
  const { data, error, response } = await api.POST('/api/projects/{name}/scaffold', {
    params: { path: { name: project } },
    body: opts,
  });
  if (error) {
    // The server emits 409 + JSON {clashes:[...], error:"..."} on path
    // collisions. openapi-fetch routes that into `error` (typed as the
    // problem+json ErrorModel), but the wire payload still carries our
    // huma-typed `clashes` field — read it via a tolerant cast.
    const body = error as { clashes?: unknown; error?: string; detail?: string };
    if (response.status === 409 && Array.isArray(body?.clashes)) {
      const clashes = body.clashes as string[];
      throw new ScaffoldClashError(
        clashes,
        body.error ?? `apply-scaffold: ${clashes.length} clashes`,
      );
    }
    const msg = body?.error ?? body?.detail ?? JSON.stringify(error);
    throw new Error(msg);
  }
  return data;
}

// --- Admin email config -----------------------------------------------

export interface EmailConfig {
  configured: boolean;
  from: string;
}

export async function getEmailConfig(): Promise<EmailConfig> {
  const { data, error } = await api.GET('/api/admin/email/config');
  if (error) throw new Error(`admin-email-config: ${JSON.stringify(error)}`);
  return { configured: data.configured, from: data.from ?? '' };
}

// --- Admin OCI images -------------------------------------------------
//
// Per-language compile image health. AdminPanel polls this on open
// and on the explicit Refresh button (force=true bypasses the
// 5-minute server-side cache).

export type OciImageStatusKind = 'ok' | 'missing' | 'unauthorized' | 'unreachable';

export interface OciImageStatus {
  language: string;
  image: string;
  status: OciImageStatusKind;
  last_checked_unix: number;
  detail?: string;
}

export async function listOCIImages(force = false): Promise<OciImageStatus[]> {
  const { data, error } = await api.GET('/api/admin/oci-images', {
    params: { query: force ? { force: true } : {} },
  });
  if (error) throw new Error(`admin-oci-images: ${JSON.stringify(error)}`);
  // The wire schema types `status` as plain string ; narrow to the
  // four documented states so the AdminPanel switch stays exhaustive.
  return (data.images ?? []) as OciImageStatus[];
}

// --- Notebook execution -----------------------------------------------
//
// One-shot exec of a code cell via the workspace μVM. The server
// dispatches via NATS to the per-project workspace and replies with
// stdout/stderr + exit code. NotebookEditor wires this to the Run
// button on each code cell.

export interface NotebookExecBody {
  language: string;
  source: string;
}

export interface NotebookExecResult {
  stdout: string;
  stderr: string;
  exit_code: number;
}

export async function execNotebook(
  project: string,
  body: NotebookExecBody,
): Promise<NotebookExecResult> {
  const { data, error } = await api.POST('/api/projects/{name}/notebook/exec', {
    params: { path: { name: project } },
    body,
  });
  if (error) throw new Error(`notebook-exec: ${JSON.stringify(error)}`);
  return {
    stdout: data.stdout,
    stderr: data.stderr,
    exit_code: data.exit_code,
  };
}

// --- Chat -------------------------------------------------------------
//
// Two surfaces :
//
//   chatStub()     — non-streaming, hits /api/projects/{name}/chat
//                    (huma-typed). The server-side handler is
//                    intentionally a canned reply that demonstrates the
//                    assistant has access to the user's file context.
//                    Useful for tests + offline demos. Kept exported so
//                    consumers that want a deterministic answer (e.g.
//                    snapshot tests) can opt in.
//
//   chatComplete() — non-streaming wrapper around the *real* provider
//                    path. Internally POSTs to the SSE
//                    /api/projects/{name}/ai/chat endpoint, accumulates
//                    the streamed tokens, and resolves with the
//                    concatenated reply. 503 from the server (no
//                    provider configured) surfaces as a typed
//                    ChatProviderUnavailableError so callers can render
//                    the "set OLLAMA_URL / ANTHROPIC_API_KEY" hint
//                    instead of a generic failure.
//
//   chatStream()   — same upstream endpoint, but invokes onToken for
//                    each chunk so the AIChatPanel-style live-typing
//                    UX can be implemented without re-deriving the SSE
//                    framing each time. Resolves with the final
//                    concatenated text.
//
// The streaming endpoint is raw (NOT in api.gen.ts) because SSE doesn't
// fit openapi-fetch's typed envelope ; we hand-roll the fetch + reader.

export interface ChatStubMessage {
  role: string;
  content: string;
}

export interface ChatStubBody {
  messages: ChatStubMessage[];
  file?: string;
  file_content?: string;
}

export interface ChatStubReply {
  reply: string;
  model?: string;
}

export async function chatStub(
  project: string,
  body: ChatStubBody,
): Promise<ChatStubReply> {
  const { data, error } = await api.POST('/api/projects/{name}/chat', {
    params: { path: { name: project } },
    body,
  });
  if (error) throw new Error(`chat-stub: ${JSON.stringify(error)}`);
  return { reply: data.reply, model: data.model };
}

// ChatProviderUnavailableError : surfaced when /ai/chat returns 503.
// `hint` carries the operator-actionable message from the server
// (install Ollama / set ANTHROPIC_API_KEY) ; `stubReply` is the canned
// answer the server fell back to so the UI can still show something.
export class ChatProviderUnavailableError extends Error {
  hint: string;
  stubReply: string;
  constructor(hint: string, stubReply: string) {
    super(stubReply || hint || 'AI provider not configured');
    this.name = 'ChatProviderUnavailableError';
    this.hint = hint;
    this.stubReply = stubReply;
  }
}

interface SsePayload {
  type: 'data' | 'done' | 'error';
  text: string;
}

// parseSseStream : pulls SSE events off `body` and yields one
// SsePayload per event. Handles both `data: <json-string>\n\n` and
// `event: error\ndata: <json-string>\n\n` framing (the shape
// internal/server/api_chat.go emits). Lifted out of AIChatPanel so
// chatComplete + chatStream share one parser.
async function* parseSseStream(body: ReadableStream<Uint8Array>): AsyncGenerator<SsePayload> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buf = '';
  while (true) {
    const { value, done } = await reader.read();
    if (done) return;
    buf += decoder.decode(value, { stream: true });
    let idx;
    while ((idx = buf.indexOf('\n\n')) !== -1) {
      const block = buf.slice(0, idx);
      buf = buf.slice(idx + 2);
      let eventName = 'message';
      let dataLine = '';
      for (const line of block.split('\n')) {
        if (line.startsWith('event:')) eventName = line.slice(6).trim();
        else if (line.startsWith('data:')) dataLine += line.slice(5).trim();
      }
      let payloadText = dataLine;
      try { payloadText = JSON.parse(dataLine); } catch { /* keep raw */ }
      if (eventName === 'done') {
        yield { type: 'done', text: '' };
        return;
      }
      if (eventName === 'error') {
        yield { type: 'error', text: String(payloadText) };
        return;
      }
      if (dataLine) yield { type: 'data', text: String(payloadText) };
    }
  }
}

export interface ChatBody {
  messages: ChatStubMessage[];
  file?: string;
  file_content?: string;
}

export interface ChatStreamOptions {
  signal?: AbortSignal;
  // onToken : invoked for each streamed chunk in arrival order.
  // Concatenating every chunk yields the same string chatComplete
  // resolves with. Errors thrown from onToken abort the stream.
  onToken?: (token: string) => void;
}

// chatStream POSTs to the SSE /ai/chat endpoint and invokes onToken
// for each streamed chunk. Resolves with the full concatenated reply.
// Throws ChatProviderUnavailableError on 503 ; Error on any other
// non-OK status. The AbortSignal cancels the in-flight fetch.
export async function chatStream(
  project: string,
  body: ChatBody,
  opts: ChatStreamOptions = {},
): Promise<string> {
  const resp = await fetch(
    `/api/projects/${encodeURIComponent(project)}/ai/chat`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: opts.signal,
    },
  );
  if (resp.status === 503) {
    // 503 body is JSON, not SSE — see internal/server/api_chat.go
    // streamProviderStub branch.
    const j = (await resp.json().catch(() => ({}))) as {
      hint?: string;
      reply?: string;
      error?: string;
    };
    throw new ChatProviderUnavailableError(
      j.hint ?? j.error ?? 'AI provider not configured',
      j.reply ?? '',
    );
  }
  if (!resp.ok || !resp.body) {
    throw new Error(`ai-chat ${resp.status}: ${await resp.text()}`);
  }
  let full = '';
  for await (const ev of parseSseStream(resp.body)) {
    if (ev.type === 'error') throw new Error(ev.text);
    if (ev.type === 'done') break;
    full += ev.text;
    opts.onToken?.(ev.text);
  }
  return full;
}

// chatComplete : non-streaming convenience over chatStream. Same
// error semantics ; resolves with the accumulated reply once the
// upstream provider signals `done`.
export async function chatComplete(
  project: string,
  body: ChatBody,
  opts?: { signal?: AbortSignal },
): Promise<string> {
  return chatStream(project, body, { signal: opts?.signal });
}

// notifyMention enqueues an email to every @-mentioned recipient
// who is on the project's ACL. Fire-and-forget on the SPA side :
// commenters never wait on SMTP. Server returns 202 immediately ;
// SMTP runs in a background goroutine.
//
// recipientEmails is OPTIONAL — when omitted the server uses the
// subject as the email (dev mode) ; in prod the SPA fills it from
// awareness state where the peer publishes its email claim.
export async function notifyMention(
  project: string,
  body: {
    recipients: string[];
    recipient_emails?: string[];
    comment_excerpt: string;
    author_name: string;
    file_path: string;
  },
): Promise<{ notified: number }> {
  const { data, error } = await api.POST('/api/projects/{name}/notify-mention', {
    params: { path: { name: project } },
    body,
  });
  if (error) throw new Error(`notify-mention: ${JSON.stringify(error)}`);
  return { notified: data?.notified ?? 0 };
}
