/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/arxiv/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search arXiv.org
         * @description Server-side proxy for arXiv's Atom-XML query API. Parses the upstream feed + returns a compact JSON envelope so the SPA doesn't pull a full XML parser into the bundle.
         */
        get: operations["arxiv-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's projects */
        get: operations["list-projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/bib/from-doi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a BibTeX entry from a DOI
         * @description Resolves a DOI through doi.org's content-negotiation API + appends the returned BibTeX to the target .bib (refs.bib by default).
         */
        post: operations["bib-from-doi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a compile job
         * @description Schedules an ephemeral compile in the language's sandbox image. Returns the job ID immediately ; logs + result stream over Server-Sent Events at /api/projects/{name}/compile/{id} (raw, outside the typed API).
         */
        post: operations["start-compile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files in a project
         * @description Returns every file in the project as a flat list with relative paths. Directories appear with dir=true. Binary read/write of one file lands on /api/projects/{name}/files/{path...} (raw, outside the typed API).
         */
        get: operations["list-files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a file's snapshot timeline
         * @description Returns the per-file edit history (newest first). Content is elided ; use the snapshot endpoint to fetch a single revision's text. Refuses .weft-loom/ paths (returns an empty list).
         */
        get: operations["list-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff two snapshots (or one snapshot vs the live file)
         * @description When `to` is omitted or equal to `live`, the right-hand side is the current on-disk file.
         */
        get: operations["diff-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach / rename / clear a label on a snapshot
         * @description Empty `label` clears the existing label.
         */
        post: operations["set-history-label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a file to a prior snapshot
         * @description Writes the snapshot's content back to the live file. Returns 204 on success. Refuses .weft-loom/ paths with 403 — pre-fix snapshots predate the privilege-escalation guard in handleWriteFile.
         */
        post: operations["restore-history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/history/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one snapshot's full content */
        get: operations["get-history-snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/public-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current public-share token for the project
         * @description Returns the token + shareable URL when one exists ; 404 when the project has no active share.
         */
        get: operations["get-public-share"];
        put?: never;
        /**
         * Issue (or rotate) a public-share token for the project
         * @description Generates a fresh 32-hex-char token + persists the sidecar. If a token already existed for this project it is replaced (the prior URL stops working). Returns the new token, its shareable URL, and the RFC3339 issue time.
         */
        post: operations["create-public-share"];
        /**
         * Revoke the public-share token for the project
         * @description Removes the sidecar + drops the token from the in-memory index. Idempotent — returns 204 even when no share existed.
         */
        delete: operations["delete-public-share"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sharing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the ACL entries for a project
         * @description Returns the per-project share list. Any authed caller can GET — collaborators need to see whom else a project is shared with.
         */
        get: operations["list-sharing"];
        put?: never;
        /**
         * Invite or update a share entry
         * @description Adds a new ACL entry or replaces the role of an existing one. Only the project owner may mutate the ACL ; the first caller of a mutating endpoint becomes the owner.
         */
        post: operations["upsert-sharing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sharing/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a share entry
         * @description Idempotent : returns 204 whether or not the user was on the ACL. Only the project owner may mutate.
         */
        delete: operations["delete-sharing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/zotero/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relay a Zotero library export as BibTeX
         * @description Hits api.zotero.org/users/<id>/items?format=bibtex with the caller-supplied API key + streams the raw BibTeX bytes back. Response Content-Type is text/plain ; the SPA appends the result to refs.bib via the file API.
         */
        post: operations["zotero-sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiffLine: {
            kind: string;
            /** Format: int64 */
            newLineNum: number;
            /** Format: int64 */
            oldLineNum: number;
            text: string;
        };
        DiffSummary: {
            /** Format: int64 */
            added: number;
            /** Format: int64 */
            removed: number;
        };
        DoiToBibInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DoiToBibInputBody.json
             */
            readonly $schema?: string;
            /** @description DOI in bare form (10.NNNN/suffix) or as a doi.org URL */
            doi: string;
            /** @description Optional target .bib file ; defaults to the first .bib in the project or refs.bib */
            target?: string;
        };
        Entry: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Entry.json
             */
            readonly $schema?: string;
            author: string;
            content?: string;
            label?: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            ts: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FileOut: {
            /** @description True when the entry is a directory */
            dir: boolean;
            /** @description Path relative to the project root */
            path: string;
            /**
             * Format: int64
             * @description Size in bytes
             */
            size: number;
        };
        HistoryDiffOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryDiffOutputBody.json
             */
            readonly $schema?: string;
            from: string;
            hunks: components["schemas"]["Hunk"][] | null;
            summary: components["schemas"]["DiffSummary"];
            to: string;
        };
        HistoryEntryOut: {
            author?: string;
            label?: string;
            /** Format: int64 */
            size: number;
            /**
             * Format: date-time
             * @description RFC3339Nano timestamp
             */
            ts: string;
        };
        HistoryLabelInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryLabelInputBody.json
             */
            readonly $schema?: string;
            at: string;
            file: string;
            /** @description New label ; empty clears */
            label: string;
        };
        HistoryLabelOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryLabelOutputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            at: string;
            label: string;
        };
        HistoryListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryListOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["HistoryEntryOut"][] | null;
        };
        HistoryRestoreInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HistoryRestoreInputBody.json
             */
            readonly $schema?: string;
            at: string;
            file: string;
        } & {
            [key: string]: unknown;
        };
        Hunk: {
            lines: components["schemas"]["DiffLine"][] | null;
            /** Format: int64 */
            newStart: number;
            /** Format: int64 */
            oldStart: number;
        };
        ListFilesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListFilesOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["FileOut"][] | null;
        };
        ListProjectsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListProjectsOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ProjectOut"][] | null;
        };
        ProjectOut: {
            /**
             * Format: date-time
             * @description Last modification time of the project directory
             */
            created_at: string;
            /** @description Detected language hint (latex / go / cpp / python / rust / javascript / markdown) */
            language?: string;
            /** @description Project name (filesystem-safe identifier) */
            name: string;
        };
        PublicShareOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PublicShareOutBody.json
             */
            readonly $schema?: string;
            /** @description RFC3339 timestamp the token was issued */
            created: string;
            /** @description 32-character hex share token */
            token: string;
            /** @description Shareable URL path (/public/<token>) */
            url: string;
        };
        SharingListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SharingListOutputBody.json
             */
            readonly $schema?: string;
            shares: components["schemas"]["SharingShareOut"][] | null;
        };
        SharingShareOut: {
            /** @description editor | commenter | viewer */
            role: string;
            /** @description User subject (dex sub claim) */
            user: string;
        };
        SharingUpsertInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SharingUpsertInputBody.json
             */
            readonly $schema?: string;
            /** @description One of editor | commenter | viewer */
            role: string;
            /** @description User subject (dex sub claim) to invite or update */
            user: string;
        };
        StartCompileBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StartCompileBody.json
             */
            readonly $schema?: string;
            /** @description Bibliography processor : bibtex | biber. Defaults to bibtex. */
            bib?: string;
            /** @description Optional verbatim shell command — overrides the language's default when set. Inside the workspace μVM, the dispatcher runs sh -c <command>. */
            command?: string;
            /** @description LaTeX engine to invoke for the latex language : pdflatex | lualatex | xelatex. Defaults to pdflatex. */
            engine?: string;
            /** @description Main source file (e.g. main.tex, main.go). Per-language default applies when empty. */
            entry?: string;
            /** @description Appended to the language's default build command. */
            extra_args?: string[] | null;
            /** @description Sandbox image picker (latex / go / cpp / python / rust / javascript). Required. */
            language: string;
        };
        StartCompileOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StartCompileOutputBody.json
             */
            readonly $schema?: string;
            /** @description Job identifier ; tail logs via GET /api/projects/{name}/compile/{id} (SSE). */
            id: string;
        };
        ZoteroSyncInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ZoteroSyncInputBody.json
             */
            readonly $schema?: string;
            /** @description Zotero API key with library:read permission */
            api_key: string;
            /** @description Reserved for future use ; current API streams the raw BibTeX back to the client */
            target?: string;
            /** @description Numeric Zotero user ID (from zotero.org/settings/keys) */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "arxiv-search": {
        parameters: {
            query?: {
                /** @description Search query (passed to arXiv as all:<q>) */
                q?: string;
                /** @description Max results (default 10, capped 50) */
                max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "bib-from-doi": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoiToBibInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "start-compile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCompileBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCompileOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFilesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-history": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "diff-history": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
                /** @description RFC3339 / RFC3339Nano timestamp of the older snapshot */
                from?: string;
                /** @description RFC3339 timestamp of the newer snapshot, or 'live' (default) for the on-disk file */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDiffOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-history-label": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryLabelInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryLabelOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "restore-history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryRestoreInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-history-snapshot": {
        parameters: {
            query?: {
                /** @description File path relative to the project root */
                file?: string;
                /** @description RFC3339 / RFC3339Nano timestamp of the snapshot */
                at?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-public-share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (filesystem-safe identifier) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upsert-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SharingUpsertInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
                /** @description User subject to remove from the ACL */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "zotero-sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoteroSyncInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
